# Module: NumPy Assignments
## Lesson: NumPy


### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [18]:
import numpy as np
import random 

## using list comprehension
arr=np.array([[random.randint(1,20) for _ in range(5)] for _ in range(5)])
print(arr)
print(arr.shape)

print()
## another way to create the same array
arr2=np.random.randint(20,size=(5,5))
print(arr2)
print(arr2.shape)

print()
## Replacing all the elements in the third column with 1
arr[:,2] = 1
print(arr)


[[ 4 20 17 16  9]
 [13  4 15 16 18]
 [ 7  4  7 16 10]
 [ 5 20 12  4  2]
 [19  5 10 10  5]]
(5, 5)

[[ 4 10  2  9  4]
 [ 6 11  8 12 11]
 [ 1 14 12 14  7]
 [ 7  8 19 16  3]
 [16 17 15 17  4]]
(5, 5)

[[ 4 20  1 16  9]
 [13  4  1 16 18]
 [ 7  4  1 16 10]
 [ 5 20  1  4  2]
 [19  5  1 10  5]]


In [21]:
#Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

arr3=np.random.randint(1,16,size=(4,4))

print(arr3)

for i in range(len(arr[0])-1):
    arr3[i][i]=0

print(arr3)

[[ 1 13 15  5]
 [ 7 13 15  9]
 [ 6  5  9 12]
 [14  6 12  3]]
[[ 0 13 15  5]
 [ 7  0 15  9]
 [ 6  5  0 12]
 [14  6 12  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [27]:
arr4=np.random.randint(1,36,size=(6,6))
print(arr4,"\n")

##subarray of 3rd to 5th row and 2nd to 4th column
subarray=arr4[2:5,1:5]

print(subarray)

[[24 13 28 27 15  9]
 [31 22 13 31 31 30]
 [24 10 19 16  2 20]
 [14 22  1 30 18 23]
 [ 6 16 19 34 13 17]
 [21 22 19 30 35  6]] 

[[10 19 16  2]
 [22  1 30 18]
 [16 19 34 13]]


In [28]:
arr5=np.random.randint(100,size=(5,5))
test_subarray=np.zeros((5,5))

print(arr5,"\n\n\n")
for i in range(len(arr5[0]-1)):
    for j in range(len(arr[0]-1)):
        if i==0 or i==4:
            test_subarray[i][j]=arr5[i][j]
        elif j==0 or j==4:
            test_subarray[i][j]=arr5[i][j]

print(test_subarray)



[[68 21 42 74 44]
 [69  1 80 88 33]
 [87 50 46 97  7]
 [13 55 29 21 72]
 [91 51 48  3 78]] 



[[68. 21. 42. 74. 44.]
 [69.  0.  0.  0. 33.]
 [87.  0.  0.  0.  7.]
 [13.  0.  0.  0. 72.]
 [91. 51. 48.  3. 78.]]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [30]:
arr6=np.random.randint(100,size=(3,4))
print(arr6,"\n\n")
arr7=np.random.randint(100,size=(3,4))
print(arr7,"\n\n")

addition_array=arr6+arr7
print(addition_array,"\n\n")

subtraction_array=arr6-arr7
print(subtraction_array,"\n\n")

multiply_array=arr6*arr7
print(multiply_array,"\n\n")


division_array=arr6/arr7
print(division_array)


[[97 22 16 96]
 [ 8 58  6 27]
 [13  3 51 38]] 


[[46 23 25 99]
 [89 94 68 84]
 [91 33 83 48]] 


[[143  45  41 195]
 [ 97 152  74 111]
 [104  36 134  86]] 


[[ 51  -1  -9  -3]
 [-81 -36 -62 -57]
 [-78 -30 -32 -10]] 


[[4462  506  400 9504]
 [ 712 5452  408 2268]
 [1183   99 4233 1824]] 


[[2.10869565 0.95652174 0.64       0.96969697]
 [0.08988764 0.61702128 0.08823529 0.32142857]
 [0.14285714 0.09090909 0.61445783 0.79166667]]


In [49]:
#Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

arr8=np.random.randint(1,16,size=(4,4))
print(arr8,"\n\n")
## Row wise Sum
for i in range(len(arr8[0])):
    print(f" Sum of row{i} is {arr8[i]} = {arr8[i].sum()} \n")
    
## Column wise Sum
for i in range(len(arr8[0])):
    print(f"Sum of Column{i} is {arr8[:,i]} = {arr8[:,i].sum()} \n ")

[[ 2  1  5  2]
 [15 14 14 15]
 [12  3  1 12]
 [ 4  3  4 12]] 


 Sum of row0 is [2 1 5 2] = 10 

 Sum of row1 is [15 14 14 15] = 58 

 Sum of row2 is [12  3  1 12] = 28 

 Sum of row3 is [ 4  3  4 12] = 23 

Sum of Column0 is [ 2 15 12  4] = 33 
 
Sum of Column1 is [ 1 14  3  3] = 21 
 
Sum of Column2 is [ 5 14  1  4] = 24 
 
Sum of Column3 is [ 2 15 12 12] = 41 
 


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).


In [51]:
ar1=np.random.randint(100,size=(5,5))

for i in range(5):
    print(f"Mean of row[{i}] is {ar1[i]} = {ar1[i].mean()}")


Mean of row[0] is [15 46 99 19 16] = 39.0
Mean of row[1] is [49 29 52 31 28] = 37.8
Mean of row[2] is [95 21 73 35 23] = 49.4
Mean of row[3] is [21 25 69  9 32] = 31.2
Mean of row[4] is [80 94 12 70 21] = 55.4


In [53]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

ar2=np.random.randint(1,9,size=(3,3))

print(ar2)

normalized_array=(ar2 - ar2.mean())/ar2.std() 

print(normalized_array)

[[5 8 4]
 [2 5 5]
 [3 4 7]]
[[ 0.12700013  1.84150184 -0.44450044]
 [-1.58750159  0.12700013  0.12700013]
 [-1.01600102 -0.44450044  1.27000127]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [56]:
ar3=np.random.randint(100,size=(3,3))
print(ar3,"\n")
row_array=np.random.randint(100,size=(3,))
print(row_array,"\n\n")

## adding 1-D array to every row :
new_array=ar3+row_array

print(new_array)

[[ 2 44  8]
 [50 40 44]
 [17 84 96]] 

[86 99 76] 


[[ 88 143  84]
 [136 139 120]
 [103 183 172]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [57]:
array=np.random.randint(1,9,size=(4,4))
row_array=np.random.randint(1,9,size=(4))

subtract_array= array-row_array

print(subtract_array)

[[-4 -4  1  1]
 [-1 -4 -2  2]
 [-2  3  1  0]
 [-6 -1 -4  3]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.


In [60]:
array=np.random.randint(1,9,size=(3,3))

print(f"Determinant of matrix \n {array}\n is = {np.linalg.det(array)}")


print(f"Inverse of matrix is :\n {np.linalg.inv(array)}")

print(f"Eigenvalues are :\n {np.linalg.eigvals(array)}")

Determinant of matrix 
 [[3 1 4]
 [6 4 7]
 [1 4 8]]
 is = 51.00000000000002
Inverse of matrix is :
 [[ 0.07843137  0.15686275 -0.17647059]
 [-0.80392157  0.39215686  0.05882353]
 [ 0.39215686 -0.21568627  0.11764706]]
Eigenvalues are :
 [ 1.00340515+1.70830656j  1.00340515-1.70830656j 12.99318971+0.j        ]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [61]:
ar1=np.random.randint(1,9,size=(2,3))
ar2=np.random.randint(1,9,size=(3,2))

result = np.dot(ar1, ar2)

print(f"Multiplication of two matirix is \n{result}")

Multiplication of two matirix is 
[[12 41]
 [15 55]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).


In [64]:
array=np.random.randint(1,9,size=(3,3))
print(array)

# Reshaping the array from (3,3) to (1,9)
array=array.reshape(1,9)

print(array)


#Reshaping the array from (1,9) to (9,1)
array=array.reshape(9,1)
print(array)

[[5 4 6]
 [3 7 8]
 [2 6 5]]
[[5 4 6 3 7 8 2 6 5]]
[[5]
 [4]
 [6]
 [3]
 [7]
 [8]
 [2]
 [6]
 [5]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [65]:
array=np.random.randint(1,9,size=(5,5))
print(array)

## Flattening the array

array=array.reshape(1,25)
print(array)

#3 Getting the back to shape (5,5)
array=array.reshape(5,5)

print(array)

[[8 7 6 8 2]
 [3 4 3 1 5]
 [4 4 2 7 1]
 [4 1 7 2 4]
 [8 3 6 3 5]]
[[8 7 6 8 2 3 4 3 1 5 4 4 2 7 1 4 1 7 2 4 8 3 6 3 5]]
[[8 7 6 8 2]
 [3 4 3 1 5]
 [4 4 2 7 1]
 [4 1 7 2 4]
 [8 3 6 3 5]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.


In [66]:
array=np.random.randint(1,9,size=(5,5))
print(array)

corner_elements=array[[0,0,-1,-1],[0,-1,0,-1]]

print(corner_elements)


[[8 7 2 1 6]
 [1 4 2 1 5]
 [7 3 5 3 8]
 [6 6 8 1 5]
 [3 3 5 8 8]]
[8 6 3 8]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [68]:
array=np.random.randint(20,size=(4,4))
print(array)

array[array>10]=10

print(array)

[[18 17 18  9]
 [18  9 19 15]
 [15 18 16  2]
 [ 5  1 18 12]]
[[10 10 10  9]
 [10  9 10 10]
 [10 10 10  2]
 [ 5  1 10 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.


In [74]:
data_type=[('name','U10'),('age','i4'),('weight','f4')]

Structured_array=np.array([('Himanshu',27,67.9),('Satyam',27,65.5),('Shivam',27,58)],dtype=data_type)

print(Structured_array)


##Sorting the array
sorted_data=np.sort(Structured_array,order='weight')
print(sorted_data)

[('Himanshu', 27, 67.9) ('Satyam', 27, 65.5) ('Shivam', 27, 58. )]
[('Shivam', 27, 58. ) ('Satyam', 27, 65.5) ('Himanshu', 27, 67.9)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [75]:
data_type=[('x','i4'),('y','i4')]
array=np.array([(3,4),(10,32),(55,34)],dtype=data_type)

print(array)

## computing the eclidean distance 




[( 3,  4) (10, 32) (55, 34)]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.